// In this Kata, you will write a function doubles that will remove double string characters that are adjacent to each other.


function doubles(s){
    let flag = false;

    for (let x = 0; x < s.length; ) {
        if (s[x] == s[x + 1]) {
            s = s.slice(0, x) + s.slice(x + 2, s.length);
            flag = true;
        } else {
            x++;
        }
    }
    return !flag ? s : doubles(s);
}


console.log(doubles('zzzzykkkd')); //,'ykd')
console.log(doubles('vvvvvoiiiiin')); //,'voin')

let tester = "zqqbcclnkktssvbeefccggoozyylwwziiookkxjvnzcclccggdpssqqvxuukkwwryyztsstpsswwdlssyyuuiihtpjzeessoofmmiilfvccdpdmmssyykkwwtcciidkkyyheehmmeeaammlnwwjeenhnnyyhlhlzcclxccplmmoofwwvzptnoojrdaammyyvuuaaggntlmmmmyymmggxfvtssssmmpwwhccuuggggldvfyyyyxuuoohxaabccmmooroooodoojwwwwvxoofyyssdyybpdaazjqqjpaafssiiwwzkknyyyyfbggggteedsszmmrkkbooheejjvtjiiuubccqqiigglyyooyyoobxvqqaanaaqqprlprlssbvpiivuufbnccxjggnmmuuggxblggssccdssyyaauuzssmmuurhyyyyoofsswwmmvgglgghwwhbdaayytssvjsssszggccmmgglyybjqqeerqqtccccpdjxbhiinryyaabnzyyyyggrkkvxjzqqyytleesseepmmvpaaxtkkxwwqqbqqxmmdmmjaapxfsswwluucceejxaabtssooeeaajuuiiziiyyhheediissjiipxhggpdliijjjrzaaggoojnhyyuudjxsshyyeedxnuuyyyyhyyqqlzggxxhbggmmccuutggmmjbwwwwyynkklxdbwwxrccfluudvkksseeuuyyoonqquuaavzccpxyymmfnqqnssvvxbuummhjmmjuussvcchpggpxqqfiitxccyyrzpvyyqqlqqkkkkeevssvaavdoouueedzpfoonoosskkvrvxssfggxeedaahvooyykkxqqaauukkuurrvwwdtzrduummaadwwyyzssoosstrwwdpmmmmmmeewwvfeeaabaakklwwkkrttaafsspuuooccuuziiggtlfxuueesseekkbqqltrhggnlpssqqxfftoommyyssfeeyyeeuujggjveekkccccdyybaayyssjaapdboofdrhggssuudaaraaloohrtpzssoooosswwuujjuuuussvssxeeaaggeeeepvbhuuggtggwwtwwmmssyyzeenoojiiaarxccjkkfoocctmmfccziiuukkrlrtlfkkkkfeeuutoowwbssmmsswweeoossmmkkeedtjzeeprkktxrggjrooaahaatdqqcclaafhnpkkkkuubeevwwssmmjtwwccggtlzmmggggzoosshjuuoossxooeeiiaanwwtprbpeewwddboommwwaammqqsscchmmeejfncctggggzoowwhqqxuuyyrmmpmmrxwweeqqpooggeehkkhiikkpxoosseetryygguuiipbaaccnyyuuqqiioormmvqqvjjzxvmmuudxjyybftooccccjlmmuuzyyqqjtpqqeepkkccrphiiiinssfooxyyvssgguurmmkkoorjggpnxljggvssrtjaaccbbiildtdpveeccqqztiipnqqlncchjmmuussggbmmooddrfpvpfxooaaaaeeaauuyyeepfwwmmqqloovjuuthaaleewwphbpmmeeffjggtaabuujdxvtmmkkmmxyyyyrqqzmmlvyyjmmzwwnjsspggzblmmbssvssxnssmmyyaavyyoossryypdmmmmuurdqqzrkkbjyyfaauuhtxxreemmccrwwqqljdmmfccmmeeoooojptmmrggwwcceeaajmmfaaiitmmjkkssccmmrvxccqquueepuueertrssxkkziipvn";

let myAns = doubles(tester);
let ans = 'zblntvbfzlzxjvnzldpvxrzpdlhtpjzflfvdpdtdlnjnlhlzlxplfvzptnjrdvntlxfvtphldvfxhxbrdjvxfdbpdzpfznfbtdzrbhvtjblbxvnprlprlbvpvfbnxjnxbldzrhfvlbdtvjzlbjrtpdjxbhnrbnzrvxjztlpvpxtxbxdjpxfljxbtjzdjpxhpdljrzjnhdjxhdxnhlzhbtjbnlxdbxrfldvnvzpxfxbhvhxftxrzpvlvzpfnvrvxfxdhvxvdtzrztrdpvfblrfpztlfxbltrhnlpxtfvdbjpdbfdrhdrlhrtpzvxpvbhznjrxjftfzrlrtltbdtjzprtxrjrhtdlfhnpbvjlhjxntprbpbhjfntzhxrprtrpbnrzxvdxjbftjlzjtrphnfxvjpnxljvrtjldtdpvztpnlnhjbrfpvpfxpflvjthlphbpjtbjdxvtxrzlvjznjpzblbvxnvrpdrdzrbjfhtljdfjptrjftjrvxprtrxzpvn';
console.log(myAns == ans);
